spring.application.name=study-apir
# pede no CP
server.port=9000
# documentação a partir do / (raiz)
springdoc.swagger-ui.path=/
# evitando hardcode 
api.version=v1

# banco de dados - configuração 
spring.datasource.url=jdbc:mysql://localhost:3306/api?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root_pwd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
