spring.application.name=study-apir
# pede no CP
server.port=8080
# documentação a partir do / (raiz)
springdoc.swagger-ui.path=/
# evitando hardcode 
api.version=v1

# banco de dados - configuração 
spring.datasource.url=jdbc:mysql://${DB_SERVER_URL}:${DB_SERVER_PORT}/${DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
